### ISSUE TITLE
Suggestion for role replacement

### ISSUE THREAD

**Issue by louanfontenele** [crimilo/Discord-Mirror#9]
Enable to do this on multiple discord servers.

I noticed that unfortunately it only seems to be able to do this on one server, it would be nice to have something to do on multiple servers. Since mirroring works for multiple servers.

It could even change to put the replacement option to do this within the mirroring part.

**Comment by crimilo** [comment]
You already can, you just need to configure the bot properly, see the following example:

|          | Server Id | Role Id 1 | Role Id 2 |
|----------|-----------|-----------|-----------|
| **SERVER 1** | 1         | 3         | 4         |
| **SERVER 2** | 2         | 5         | 6         |

```json
"mentions": {
   "1": [
      {
         "original": "3",
         "replaced": "5"
      }
   ],
   "2": [
      {
         "original": "6",
         "replaced": "4"
      }
   ]
}
```
When a message in the server **1** contains a mention to the role **3**, the mirrored message will replace it with role **5** (the mirrored message should be sent in server **2** in this case, since its there where the role **5** exists).

When a message in the server **2** contains a mention to the role **6**, the mirrored message will replace it with role **4** (the mirrored message should be sent in server **1** in this case, since is there where the role **4** exists).
